### ISSUE TITLE
Paginator Support

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy-kotlin#543] opened 2021-11-30 17:50 UTC
Acceptance Criteria: implement the [paginator design](https://github.com/awslabs/smithy-kotlin/blob/main/docs/design/paginators.md)

**Comment by aajtodd** [comment] 2021-12-03 19:30
Duplicate of https://github.com/awslabs/smithy-kotlin/issues/124

**Closed** 2021-12-16 17:05 UTC
Labels: feature
